### ISSUE TITLE
Missing verification_status property in CheckKYC response

### ISSUE THREAD

**Issue by mlegui21** [Sila-Money/sila-sdk-csharp#7]
Could you add the verification_status when you return the response of CheckKYC?

**Comment by chepix10** [comment]
Thanks for the report @mlegui21 
This will be resolved with #8

**Comment by chepix10** [comment]
@mlegui21 You can try with version [0.2.12-rc](https://www.nuget.org/packages/Sila.SDK/0.2.12-rc)
